import type { AuditReport } from "./types";
import { CATEGORY_LABELS, ENGINES, ENGINE_LABELS } from "./types";
import { SUB_LABELS } from "./blocks";

export function reportToMarkdown(r: AuditReport): string {
  const e = r.evidence;
  const L: string[] = [];

  L.push(`# GEO audit — ${e.html.title ?? e.finalUrl}`);
  L.push("");
  L.push(`**URL:** ${e.finalUrl}`);
  L.push(`**Audited:** ${new Date(e.fetchedAt).toUTCString()}`);
  L.push(`**Overall Visibility Score:** ${r.visibility?.overall ?? r.composite}/100`);
  L.push(`- SEO: ${r.visibility?.seo ?? 0}/100`);
  L.push(`- GEO / AI Search: ${r.visibility?.geo ?? r.composite}/100`);
  L.push(`- AI Crawlers: ${r.visibility?.crawlers ?? 0}/100`);
  L.push(`- Technical: ${r.visibility?.technical ?? 0}/100`);
  L.push(`- Content: ${r.visibility?.content ?? 0}/100`);
  L.push(`- Schema: ${r.visibility?.schema ?? 0}/100`);
  L.push("");
  L.push(`**Composite GEO:** ${r.composite}/100 · **Spread:** ${r.spread} points`);
  L.push("");
  L.push(r.summary);
  L.push("");

  L.push("## Score by engine");
  L.push("");
  L.push("| Engine | Score | Note |");
  L.push("|---|---:|---|");
  for (const engine of ENGINES) {
    const s = r.engines[engine];
    L.push(
      `| ${ENGINE_LABELS[engine]} | ${s.score} | ${s.capped ? `Capped — ${s.capReason}` : "—"} |`,
    );
  }
  L.push("");

  L.push("## Category scores");
  L.push("");
  L.push("| Category | Score |");
  L.push("|---|---:|");
  for (const c of Object.keys(CATEGORY_LABELS) as (keyof typeof CATEGORY_LABELS)[]) {
    const relevant = r.checks.filter((x) => x.category === c && x.weight > 0 && x.status !== "na");
    const tw = relevant.reduce((n, x) => n + x.weight, 0);
    const v = tw ? Math.round((relevant.reduce((n, x) => n + x.value * x.weight, 0) / tw) * 100) : 0;
    L.push(`| ${CATEGORY_LABELS[c]} | ${v} |`);
  }
  L.push("");

  L.push("## Findings");
  L.push("");
  if (r.findings.length === 0) {
    L.push("No findings — every weighted check passed.");
  }
  for (const f of r.findings) {
    L.push(`### [${f.severity.toUpperCase()}] ${f.fix.summary}`);
    L.push("");
    L.push(`- **Category:** ${CATEGORY_LABELS[f.category]}`);
    L.push(`- **Effort:** ${f.effort}`);
    L.push(
      `- **Engines affected:** ${f.engines.length === 5 ? "all five" : f.engines.map((x) => ENGINE_LABELS[x]).join(", ")}`,
    );
    L.push(`- **Evidence:** ${f.evidence}`);
    L.push("");
    L.push(f.fix.detail);
    L.push("");
  }

  if (r.weakestBlocks.length) {
    L.push("## Weakest passages");
    L.push("");
    for (const b of r.weakestBlocks) {
      L.push(`### Block ${b.id} — ${Math.round(b.scores.total * 100)}/100 (${b.words} words)`);
      L.push("");
      if (b.heading) L.push(`Under heading: *${b.heading}*`);
      L.push("");
      L.push("> " + b.text.replace(/\n/g, " ").slice(0, 700));
      L.push("");
      L.push(
        (Object.keys(SUB_LABELS) as (keyof typeof SUB_LABELS)[])
          .map((k) => `${SUB_LABELS[k]} ${Math.round(b.scores[k] * 100)}`)
          .join(" · "),
      );
      L.push("");
      for (const n of b.notes) L.push(`- ${n}`);
      L.push("");
    }
  }

  L.push("## All checks");
  L.push("");
  L.push("| Check | Status | Evidence |");
  L.push("|---|---|---|");
  for (const c of r.checks) {
    L.push(`| ${c.label} | ${c.status} | ${c.evidence.replace(/\|/g, "\\|").slice(0, 180)} |`);
  }
  L.push("");
  L.push("---");
  L.push("");
  L.push(
    `Generated by Crawlspace v${r.version}. Weights and method: https://crawlspace-geo.vercel.app/methodology`,
  );

  return L.join("\n");
}

/**
 * Engineered Prompt for LLMs (Claude, ChatGPT, etc.)
 * Provides the entire audit diagnostic context and asks the LLM to write exact code and fixes.
 */
export function reportToLLMPrompt(r: AuditReport): string {
  const e = r.evidence;
  const critical = r.findings.filter((f) => f.severity === "critical" || f.severity === "high");
  const warnings = r.findings.filter((f) => f.severity === "medium");

  const L: string[] = [];

  L.push("You are a Principal Web Architect, Senior Technical SEO Specialist, and Generative Engine Optimization (GEO) expert.");
  L.push(`I have audited the webpage at ${e.finalUrl} using Crawlspace Website Visibility Intelligence.`);
  L.push("");
  L.push("Your task: Provide concrete code, structured data, robots directives, and rewritten copy to fix all identified issues and maximize this page's visibility and citations across Google Search, ChatGPT, Perplexity, Claude, and Copilot.");
  L.push("");
  L.push("---");
  L.push("");
  L.push("### 1. AUDIT SNAPSHOT");
  L.push(`- Page Title: ${e.html.title ?? "(missing)"}`);
  L.push(`- Final URL: ${e.finalUrl}`);
  L.push(`- Word Count: ${e.html.textWords} words (${e.html.htmlBytes} bytes HTML)`);
  L.push(`- Overall Visibility Score: ${r.visibility?.overall ?? r.composite}/100`);
  L.push(`  * SEO Score: ${r.visibility?.seo ?? 0}/100`);
  L.push(`  * GEO / AI Search: ${r.visibility?.geo ?? r.composite}/100`);
  L.push(`  * AI Crawler Access: ${r.visibility?.crawlers ?? 0}/100`);
  L.push(`  * Technical Health: ${r.visibility?.technical ?? 0}/100`);
  L.push(`  * Content Intelligence: ${r.visibility?.content ?? 0}/100`);
  L.push(`  * Structured Data (Schema): ${r.visibility?.schema ?? 0}/100`);
  L.push("");
  L.push(`Composite Engine Citability Scores:`);
  for (const engine of ENGINES) {
    const s = r.engines[engine];
    L.push(`  * ${ENGINE_LABELS[engine]}: ${s.score}/100 ${s.capped ? `(Capped: ${s.capReason})` : ""}`);
  }
  L.push("");
  L.push("---");
  L.push("");
  L.push("### 2. PRIORITY ISSUES TO RESOLVE");
  if (critical.length === 0 && warnings.length === 0) {
    L.push("No critical or high issues found.");
  } else {
    for (const f of [...critical, ...warnings]) {
      L.push(`#### [${f.severity.toUpperCase()}] ${f.label}`);
      L.push(`- Category: ${CATEGORY_LABELS[f.category]}`);
      L.push(`- Evidence on page: ${f.evidence}`);
      L.push(`- Fix directive: ${f.fix.summary}`);
      L.push(`- Technical details: ${f.fix.detail}`);
      L.push("");
    }
  }

  L.push("---");
  L.push("");
  L.push("### 3. STRUCTURED DATA & SCHEMA.ORG");
  L.push(`Detected Schema Types: ${e.schemaAnalysis?.detectedTypes?.join(", ") || "None"}`);
  if (e.schemaAnalysis?.issues?.length) {
    L.push("Identified Schema Issues:");
    for (const issue of e.schemaAnalysis.issues) {
      L.push(`- ${issue}`);
    }
  }
  L.push("");
  L.push("Action needed: Write complete, valid JSON-LD (<script type=\"application/ld+json\">) incorporating Organization, WebPage/Article, and FAQPage schemas tailored specifically to this URL.");
  L.push("");

  if (r.weakestBlocks.length) {
    L.push("---");
    L.push("");
    L.push("### 4. WEAK CONTENT PASSAGES TO REWRITE (FOR AI CITATION)");
    L.push("These passages fail AI extractability tests due to deixis (vague pronouns like 'this', 'it' without antecedents), buried claims, or low factual density. Rewrite each block so it is self-contained, leads with an assertive answer, and maintains factual accuracy without hallucinating fake numbers:");
    L.push("");
    for (const b of r.weakestBlocks.slice(0, 4)) {
      L.push(`Block [${b.id}] (Score: ${Math.round(b.scores.total * 100)}/100):`);
      if (b.heading) L.push(`Heading context: "${b.heading}"`);
      L.push(`Original Text:\n> ${b.text.replace(/\n/g, " ").slice(0, 500)}`);
      L.push(`Diagnostic notes: ${b.notes.join("; ")}`);
      L.push("");
    }
  }

  L.push("---");
  L.push("");
  L.push("### 5. ROBOTS & AI CRAWLER CONFIGURATION");
  L.push(`Robots.txt status: ${e.robots.found ? "Found" : "Missing"}`);
  L.push("Action needed: Provide recommended robots.txt entries that allow AI search crawlers (OAI-SearchBot, ClaudeBot, PerplexityBot, Googlebot, Bingbot) while safely blocking training-only web scrapers (such as CCBot).");
  L.push("");
  L.push("Please provide the solution organized into 4 sections: 1. HTML Meta & Header Tags, 2. Complete JSON-LD Script, 3. Content Block Rewrites, 4. Robots.txt Snippet.");

  return L.join("\n");
}

export function reportToJson(r: AuditReport): string {
  return JSON.stringify(r, null, 2);
}

export function download(filename: string, content: string, type: string): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function safeFilename(url: string): string {
  try {
    const u = new URL(url);
    return (u.hostname + u.pathname).replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").slice(0, 60);
  } catch {
    return "audit";
  }
}
