import type { AuditReport } from "./types";
import { CATEGORY_LABELS, ENGINES, ENGINE_LABELS } from "./types";
import { SUB_LABELS } from "./blocks";

export function reportToMarkdown(r: AuditReport): string {
  const e = r.evidence;
  const L: string[] = [];

  L.push(`# GEO audit — ${e.html.title ?? e.finalUrl}`);
  L.push("");
  L.push(`**URL:** ${e.finalUrl}`);
  L.push(`**Audited:** ${new Date(e.fetchedAt).toUTCString()}`);
  L.push(`**Composite:** ${r.composite}/100 · **Spread:** ${r.spread} points`);
  L.push("");
  L.push(r.summary);
  L.push("");

  L.push("## Score by engine");
  L.push("");
  L.push("| Engine | Score | Note |");
  L.push("|---|---:|---|");
  for (const engine of ENGINES) {
    const s = r.engines[engine];
    L.push(
      `| ${ENGINE_LABELS[engine]} | ${s.score} | ${s.capped ? `Capped — ${s.capReason}` : "—"} |`,
    );
  }
  L.push("");

  L.push("## Category scores");
  L.push("");
  L.push("| Category | Score |");
  L.push("|---|---:|");
  for (const c of Object.keys(CATEGORY_LABELS) as (keyof typeof CATEGORY_LABELS)[]) {
    const relevant = r.checks.filter((x) => x.category === c && x.weight > 0 && x.status !== "na");
    const tw = relevant.reduce((n, x) => n + x.weight, 0);
    const v = tw ? Math.round((relevant.reduce((n, x) => n + x.value * x.weight, 0) / tw) * 100) : 0;
    L.push(`| ${CATEGORY_LABELS[c]} | ${v} |`);
  }
  L.push("");

  L.push("## Findings");
  L.push("");
  if (r.findings.length === 0) {
    L.push("No findings — every weighted check passed.");
  }
  for (const f of r.findings) {
    L.push(`### [${f.severity.toUpperCase()}] ${f.fix.summary}`);
    L.push("");
    L.push(`- **Category:** ${CATEGORY_LABELS[f.category]}`);
    L.push(`- **Effort:** ${f.effort}`);
    L.push(
      `- **Engines affected:** ${f.engines.length === 5 ? "all five" : f.engines.map((x) => ENGINE_LABELS[x]).join(", ")}`,
    );
    L.push(`- **Evidence:** ${f.evidence}`);
    L.push("");
    L.push(f.fix.detail);
    L.push("");
  }

  if (r.weakestBlocks.length) {
    L.push("## Weakest passages");
    L.push("");
    for (const b of r.weakestBlocks) {
      L.push(`### Block ${b.id} — ${Math.round(b.scores.total * 100)}/100 (${b.words} words)`);
      L.push("");
      if (b.heading) L.push(`Under heading: *${b.heading}*`);
      L.push("");
      L.push("> " + b.text.replace(/\n/g, " ").slice(0, 700));
      L.push("");
      L.push(
        (Object.keys(SUB_LABELS) as (keyof typeof SUB_LABELS)[])
          .map((k) => `${SUB_LABELS[k]} ${Math.round(b.scores[k] * 100)}`)
          .join(" · "),
      );
      L.push("");
      for (const n of b.notes) L.push(`- ${n}`);
      L.push("");
    }
  }

  L.push("## All checks");
  L.push("");
  L.push("| Check | Status | Evidence |");
  L.push("|---|---|---|");
  for (const c of r.checks) {
    L.push(`| ${c.label} | ${c.status} | ${c.evidence.replace(/\|/g, "\\|").slice(0, 180)} |`);
  }
  L.push("");
  L.push("---");
  L.push("");
  L.push(
    `Generated by Crawlspace v${r.version}. Weights and method: https://crawlspace-geo.vercel.app/methodology`,
  );

  return L.join("\n");
}

export function download(filename: string, content: string, type: string): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function safeFilename(url: string): string {
  try {
    const u = new URL(url);
    return (u.hostname + u.pathname).replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").slice(0, 60);
  } catch {
    return "audit";
  }
}
