import type { AuditReport, ContentBlock, Finding } from "./types";

const mockBlock1: ContentBlock = {
  id: "b1",
  kind: "paragraph",
  heading: "Online and in-person payments",
  text: "Stripe is a suite of APIs powering online payment processing and commerce solutions for internet businesses of all sizes, from scaling startups to global enterprises.",
  words: 26,
  domPath: "main > section:first-of-type p:first-of-type",
  scores: {
    selfContainment: 0.9,
    answerDirectness: 0.92,
    lengthBand: 0.85,
    factualDensity: 0.88,
    readability: 0.9,
    total: 0.89,
  },
  notes: ["Strong self-contained assertion with clear entity definition."],
};

const mockBlock2: ContentBlock = {
  id: "b2",
  kind: "paragraph",
  heading: "Global payment methods",
  text: "As discussed above, this system processes thousands of transactions per minute with sub-second latency and automated risk evaluation across all major credit card networks.",
  words: 24,
  domPath: "main > section:nth-of-type(2) p:first-of-type",
  scores: {
    selfContainment: 0.45,
    answerDirectness: 0.6,
    lengthBand: 0.7,
    factualDensity: 0.5,
    readability: 0.65,
    total: 0.58,
  },
  notes: ["Contains 'As discussed above' (deixis penalty) which breaks out-of-context citation."],
};

const mockFindings: Finding[] = [
  {
    checkId: "ai-search-crawlers",
    label: "AI Search Crawlers are fully permitted in robots.txt",
    category: "machine-readability",
    severity: "low",
    effort: "trivial",
    engines: ["chatgpt", "claude", "perplexity", "copilot"],
    evidence: "OAI-SearchBot, ClaudeBot, and PerplexityBot have full crawl access for citations.",
    fix: {
      summary: "Keep search crawlers allowed",
      detail: "Maintain explicit allow directives for OAI-SearchBot and ClaudeBot.",
      effort: "trivial",
    },
    status: "pass",
  },
  {
    checkId: "schema-org-active",
    label: "Organization and WebSite Schema.org structured data validated",
    category: "machine-readability",
    severity: "low",
    effort: "trivial",
    engines: ["google-aio", "chatgpt", "claude", "perplexity", "copilot"],
    evidence: "Entity identity and sameAs social verification links are properly declared.",
    fix: {
      summary: "Schema active",
      detail: "All required entity attributes found.",
      effort: "trivial",
    },
    status: "pass",
  },
  {
    checkId: "missing-faq-schema",
    label: "Missing FAQPage structured data schema",
    category: "machine-readability",
    severity: "medium",
    effort: "medium",
    engines: ["google-aio", "chatgpt", "perplexity"],
    evidence: "Documentation overview contains question-answer pairs that lack FAQPage JSON-LD markup.",
    fix: {
      summary: "Add FAQPage JSON-LD",
      detail: "Add FAQPage schema block with Question and Answer mainEntity definitions.",
      effort: "medium",
      generates: "jsonld",
    },
    status: "warn",
  },
  {
    checkId: "deixis-intro",
    label: "Opening passage contains vague deixis without self-contained antecedent",
    category: "extractability",
    severity: "critical",
    effort: "small",
    engines: ["chatgpt", "claude", "perplexity", "copilot"],
    evidence: "First paragraph begins with 'As discussed previously, this API...', losing context when quoted.",
    fix: {
      summary: "Rewrite opening passage to state entity directly",
      detail: "Replace relational pronouns with direct subject assertions: 'Stripe Payments is an API...'.",
      effort: "small",
      rewritable: true,
    },
    status: "fail",
  },
  {
    checkId: "evidence-density-lift",
    label: "Passage lacks quantitative benchmarks or statistical backing",
    category: "evidence-density",
    severity: "high",
    effort: "medium",
    engines: ["perplexity", "claude", "chatgpt"],
    evidence: "Claims about conversion rate improvements lack exact cited percentage metrics.",
    fix: {
      summary: "Add empirical metrics",
      detail: "Ground assertions with numerical evidence: 'increases authorization rates by up to 3.2%'.",
      effort: "medium",
    },
    status: "warn",
  },
];

export const SAMPLE_REPORT: AuditReport = {
  version: "1.2.0",
  composite: 78,
  spread: 8,
  summary: "Robust technical SEO and full search crawler access. Content extractability has strong upside with direct entity definitions and FAQ schema.",
  visibility: {
    overall: 78,
    seo: 84,
    geo: 71,
    crawlers: 88,
    technical: 82,
    content: 76,
    schema: 91,
  },
  engines: {
    "google-aio": { score: 80, capped: false, categories: { extractability: 80, "answer-structure": 82, "evidence-density": 78, "machine-readability": 85, authority: 88, retrievability: 84 } },
    chatgpt: { score: 76, capped: false, categories: { extractability: 74, "answer-structure": 76, "evidence-density": 72, "machine-readability": 84, authority: 82, retrievability: 80 } },
    perplexity: { score: 82, capped: false, categories: { extractability: 84, "answer-structure": 80, "evidence-density": 86, "machine-readability": 88, authority: 85, retrievability: 82 } },
    claude: { score: 78, capped: false, categories: { extractability: 78, "answer-structure": 80, "evidence-density": 76, "machine-readability": 86, authority: 84, retrievability: 80 } },
    copilot: { score: 74, capped: false, categories: { extractability: 72, "answer-structure": 75, "evidence-density": 70, "machine-readability": 82, authority: 80, retrievability: 78 } },
  },
  checks: [],
  findings: mockFindings,
  weakestBlocks: [mockBlock2],
  strongestBlock: mockBlock1,
  evidence: {
    url: "https://stripe.com/docs/payments",
    finalUrl: "https://stripe.com/docs/payments",
    status: 200,
    fetchedAt: new Date().toISOString(),
    timings: { totalMs: 142, fetchMs: 98 },
    html: {
      title: "Payments Overview · Stripe Documentation",
      metaDescription:
        "Accept payments online, in-person, and around the world with a payments solution built for any business—from scaling startups to global enterprises.",
      canonical: "https://stripe.com/docs/payments",
      lang: "en",
      viewport: "width=device-width, initial-scale=1",
      charset: "utf-8",
      htmlBytes: 48520,
      textWords: 1480,
      textBytes: 12400,
      textToHtmlRatio: 0.25,
    },
    openGraph: {
      title: "Payments Overview · Stripe Documentation",
      description: "Accept payments globally with Stripe.",
      image: "https://stripe.com/img/og-payments.png",
      type: "article",
      siteName: "Stripe",
    },
    twitter: {
      card: "summary_large_image",
      title: "Payments Overview · Stripe Documentation",
      description: "Accept payments globally with Stripe.",
      image: "https://stripe.com/img/og-payments.png",
    },
    headings: [
      { level: 1, text: "Online and in-person payments" },
      { level: 2, text: "Global payment methods" },
      { level: 2, text: "Fraud and risk prevention with Radar" },
      { level: 2, text: "Optimized checkout experiences" },
      { level: 2, text: "Subscription billing and recurring revenue" },
      { level: 2, text: "Developer integration methods" },
      { level: 2, text: "Security and PCI compliance" },
      { level: 2, text: "Reporting and financial reconciliation" },
    ],
    blocks: [mockBlock1, mockBlock2],
    jsonLd: [
      {
        types: ["Organization"],
        raw: {
          "@context": "https://schema.org",
          "@type": "Organization",
          name: "Stripe",
          url: "https://stripe.com",
          logo: "https://stripe.com/img/logo.png",
          sameAs: ["https://twitter.com/stripe", "https://github.com/stripe"],
        },
      },
      {
        types: ["WebSite"],
        raw: {
          "@context": "https://schema.org",
          "@type": "WebSite",
          name: "Stripe Documentation",
          url: "https://stripe.com/docs",
        },
      },
      {
        types: ["BreadcrumbList"],
        raw: {
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          itemListElement: [
            { "@type": "ListItem", position: 1, name: "Documentation", item: "https://stripe.com/docs" },
            { "@type": "ListItem", position: 2, name: "Payments", item: "https://stripe.com/docs/payments" },
          ],
        },
      },
    ],
    microdata: [],
    schemaAnalysis: {
      detectedTypes: ["Organization", "WebSite", "BreadcrumbList"],
      issues: ["No FAQPage schema detected on documentation overview."],
      rawSnippets: [
        `{\n  "@context": "https://schema.org",\n  "@type": "Organization",\n  "name": "Stripe"\n}`,
        `{\n  "@context": "https://schema.org",\n  "@type": "WebSite",\n  "name": "Stripe Docs"\n}`,
        `{\n  "@context": "https://schema.org",\n  "@type": "BreadcrumbList"\n}`,
      ],
    },
    robots: {
      found: true,
      status: 200,
      rules: {
        Googlebot: { agent: "Googlebot", allowed: true, reason: "Allow: /" },
        "OAI-SearchBot": { agent: "OAI-SearchBot", allowed: true, reason: "Allow: /" },
        ClaudeBot: { agent: "ClaudeBot", allowed: true, reason: "Allow: /" },
        PerplexityBot: { agent: "PerplexityBot", allowed: true, reason: "Allow: /" },
        GPTBot: { agent: "GPTBot", allowed: false, reason: "Disallow: /" },
        CCBot: { agent: "CCBot", allowed: false, reason: "Disallow: /" },
      },
      metaRobots: null,
      xRobotsTag: null,
      rawText: `User-agent: *\nAllow: /\nDisallow: /admin/\n\nUser-agent: OAI-SearchBot\nAllow: /\n\nUser-agent: ClaudeBot\nAllow: /\n\nSitemap: https://stripe.com/sitemap.xml`,
      explainedRules: [
        {
          agent: "OAI-SearchBot",
          directive: "Allow",
          path: "/",
          explanation: "Explicitly permitted to crawl content for live ChatGPT Search answers.",
          allowed: true,
        },
        {
          agent: "ClaudeBot",
          directive: "Allow",
          path: "/",
          explanation: "Explicitly permitted to crawl and cite content in Anthropic Claude responses.",
          allowed: true,
        },
        {
          agent: "GPTBot",
          directive: "Disallow",
          path: "/",
          explanation: "Blocked from scraping data for OpenAI model training.",
          allowed: false,
        },
      ],
    },
    llmsTxt: { found: true, valid: true, issues: [], bytes: 1450 },
    sitemap: { found: true, inRobots: true, urlCount: 412 },
    links: {
      internal: 38,
      external: 12,
      externalCitations: 4,
      citationDomains: ["docs.stripe.com", "pci.org", "visa.com"],
    },
    media: { images: 12, withAlt: 11 },
    dates: {
      published: "2024-01-15T00:00:00Z",
      modified: "2026-09-01T00:00:00Z",
      visibleDate: "Sep 2026",
    },
    author: { name: "Stripe Developer Platform", hasSchema: true, hasBio: true },
    semantics: {
      main: true,
      article: true,
      nav: true,
      header: true,
      footer: true,
      h1Count: 1,
      hierarchyOk: true,
    },
    signals: {
      stats: 14,
      percentages: 8,
      years: 6,
      quotes: 4,
      tables: 2,
      lists: 6,
      faqPairs: 4,
      questionHeadings: 2,
    },
    renderedWithoutJs: true,
    frameworkHint: "Next.js",
  },
};
