import type { Evidence } from "../types";

/**
 * Deterministic generation — no model involved. Everything here is filled from the
 * site's own evidence, so it works in zero-key mode and cannot hallucinate.
 */

function siteName(e: Evidence): string {
  const org = e.jsonLd.find((n) => n.types.includes("Organization"))?.raw as
    | { name?: string }
    | undefined;
  if (org?.name) return org.name;
  const title = e.html.title ?? "";
  const parts = title.split(/[|–—-]/).map((p) => p.trim()).filter(Boolean);
  if (parts.length > 1) return parts[parts.length - 1];
  try {
    return new URL(e.finalUrl).hostname.replace(/^www\./, "");
  } catch {
    return "This site";
  }
}

export function generateLlmsTxt(e: Evidence): string {
  const url = new URL(e.finalUrl);
  const name = siteName(e);
  const description =
    e.html.metaDescription?.trim() ||
    e.blocks[0]?.text.slice(0, 200) ||
    "TODO — one sentence on what this site does and who it is for.";

  const sections = e.headings
    .filter((h) => h.level === 2)
    .slice(0, 8)
    .map((h) => `- [${h.text}](${url.origin}${url.pathname}) — TODO: one line on what this covers`);

  return `# ${name}

> ${description}

${name} publishes this at ${url.origin}. This file gives AI assistants a short, accurate
summary of the site so they can answer questions about it without guessing.

## Key pages

- [${e.html.title ?? "Home"}](${e.finalUrl})
${sections.length ? sections.join("\n") : "- TODO: list your most important pages here, one per line, as markdown links."}

## About

TODO — two or three sentences: what you do, who you serve, and what makes your
information worth citing. Keep it factual. Assistants quote this.

## Contact

- Website: ${url.origin}
- TODO: add an email or contact page

<!-- Generated by Crawlspace. Replace every TODO before publishing this file. -->
`;
}

export function generateJsonLd(e: Evidence): string {
  const url = new URL(e.finalUrl);
  const name = siteName(e);
  const present = new Set(e.jsonLd.flatMap((n) => n.types));
  const graph: Record<string, unknown>[] = [];

  if (!present.has("Organization")) {
    graph.push({
      "@type": "Organization",
      "@id": `${url.origin}/#organization`,
      name,
      url: url.origin,
      logo: `${url.origin}/logo.png`,
      sameAs: [
        "https://www.linkedin.com/company/TODO",
        "https://github.com/TODO",
      ],
    });
  }

  if (!present.has("WebPage") && !present.has("Article") && !present.has("BlogPosting")) {
    graph.push({
      "@type": "WebPage",
      "@id": `${e.finalUrl}#webpage`,
      url: e.finalUrl,
      name: e.html.title ?? name,
      description: e.html.metaDescription ?? "TODO — one-sentence description of this page.",
      inLanguage: e.html.lang ?? "en",
      isPartOf: { "@id": `${url.origin}/#organization` },
      ...(e.dates.modified ? { dateModified: e.dates.modified } : { dateModified: "TODO-YYYY-MM-DD" }),
      ...(e.dates.published ? { datePublished: e.dates.published } : {}),
      ...(e.author.name
        ? { author: { "@type": "Person", name: e.author.name } }
        : { author: { "@type": "Person", name: "TODO — author name", jobTitle: "TODO — role" } }),
    });
  }

  const questionHeadings = e.headings
    .filter((h) => h.level >= 2 && (/\?$/.test(h.text) || /^(what|how|why|when|where|who|which)\b/i.test(h.text)))
    .slice(0, 6);

  if (!present.has("FAQPage") && questionHeadings.length >= 2) {
    graph.push({
      "@type": "FAQPage",
      "@id": `${e.finalUrl}#faq`,
      mainEntity: questionHeadings.map((h) => ({
        "@type": "Question",
        name: h.text.replace(/\?*$/, "?"),
        acceptedAnswer: {
          "@type": "Answer",
          text: "TODO — answer this in 40 to 60 words, stating the answer in the first sentence.",
        },
      })),
    });
  }

  if (graph.length === 0) {
    return "// This page already declares Organization, WebPage and FAQ schema. Nothing to add.";
  }

  return `<script type="application/ld+json">
${JSON.stringify({ "@context": "https://schema.org", "@graph": graph }, null, 2)}
</script>`;
}

export function generateRobotsSnippet(): string {
  return `# Allow the AI crawlers you want citations from.
# Blocking any of these means that engine cannot cite you at all.

User-agent: GPTBot
User-agent: OAI-SearchBot
User-agent: ChatGPT-User
User-agent: PerplexityBot
User-agent: Perplexity-User
User-agent: ClaudeBot
User-agent: Claude-User
User-agent: Claude-SearchBot
User-agent: anthropic-ai
User-agent: Google-Extended
User-agent: Bingbot
Allow: /

# CCBot is training-only. Blocking it costs you no citations.
User-agent: CCBot
Disallow: /

Sitemap: https://YOUR-DOMAIN/sitemap.xml`;
}
